#
# subreader Makefile
#
include $(SUBDIR)../config.mak

libsub_VERSION=0.1.0
libsub_VERSION_MAJOR=0

NAME = sub

OBJS = subreader.o

HEADERS = subreader.h

CFLAGS-yes += -DUSE_SORTSUB

include $(SRC_PATH)/subdir.mak
